blank_issues_enabled: true
contact_links:
  - name: Full Ghast Ahead on CurseForge
    url: https://www.curseforge.com/minecraft/mc-mods/full-ghast-ahead
    about: Downloads, the full description and the changelog
